### ISSUE TITLE
Decide what to do with popeye and afni HRFs

### ISSUE THREAD

**Issue by garikoitz** [vistalab/PRFmodel#4]
They are TR dependent and if they are not precomputed, they will fail.

**Comment by noahbenson** [comment]
I think I have this fixed for the popeye HRF (at least, in a test I just ran in the Docker, the py.popeye... call worked fine). AFNI is a different matter; we probably need it installed in the docker to run it properly. Let's chat about this tomorrow.

**Comment by garikoitz** [comment]
ok! they have it dockerized, but I don't know how much would be to add our
layers to theirs

https://hub.docker.com/r/afni/afni

**Comment by noahbenson** [comment]
Oh, good point; I'll take a look and see if it would be easier for us to add AFNI into our dockers rather than doing things the other way around. If we add our layers to the AFNI-docker, we will lose the flywheel base, which includes the Matlab runtime...

**Comment by garikoitz** [comment]
that's true, but do we need the Matlab base for the AFNI gear? we just need
the python and BIDs layer that you added right? so that it reads and writes
the format we want

**Comment by noahbenson** [comment]
For the AFNI docker we won't need the Matlab base, but for prfsynth we need both the matlab and the AFNI stuff (for the HRFs) right?

**Comment by garikoitz** [comment]
hmmm you are right... if we want to use different HRFs created by afni...

ok, I'll look if it is possible to isolate the executable that just creates
the HRF, if I get that, we would be good to go?

**Comment by noahbenson** [comment]
Probably, yeah!
I just glanced through the AFNI dockerfile and I think it will be possible to reproduce it inside our prfsynth docker (the whole thing if need be but ideally just some of it). I'll play around with it a bit tonight and we can discuss details tomorrow!

**Comment by garikoitz** [comment]
ok, I'll look the isolation thing for tomorrow too
I need to fix another thing in prfsynth (remove unnecessary I/O that slow
the whole thing...)

**Comment by garikoitz** [comment]
the isolation didn't work in its own, it is asking for more libraries. Noah already compiled afni for the Docker container so we'll need to decide if we maintain this functionality or not. Twogammas is twogammas regardless of it has been implemented by afni or not. It was useful for testing, but maybe not so much or the final prfsynth. Discuss with Noah and decide after he finishes with afni

**Comment by garikoitz** [comment]
both afni and python in matlab have been too complicated to implement in the docker container, they will be available to us or the users in the matlab interface if they have it installed locally. Right now we removed the option to create Afni and Popeye HRFs from prfsynth. Closing this issue
