### ISSUE TITLE
looking for the dockerfiles

### ISSUE THREAD

**Issue by Remi-Gau** [vistalab/PRFmodel#54]
Hello

Would it be possible to add to the repo the dockerfiles that were used to create the docker images?

I love docker for reproducibility :rocket: but I love it even more when I can check the recipes to know how it was built and if adding any extra layer will "mess" things up.

Thank you in advance.

**Comment by garikoitz** [comment]
Thanks for your interest in the repo Remi!
we have the Dockerfiles, for example here:
https://github.com/vistalab/PRFmodel/blob/master/gear/prfsynth/Dockerfile

let me know if you have any other question please

**Comment by Remi-Gau** [comment]
AWESOME. :star_struck: 

I guess I did not look hard enough.

I am about to embark on some pRF stuff and I don't intend to reinvent the wheel so your images will come in super handy I am sure.

:-)

**Comment by garikoitz** [comment]
:) thanks and good luck with your project!
