### ISSUE TITLE
Voxels with multiple receptive field

### ISSUE THREAD

**Issue by ustc-bmec** [vistalab/PRFmodel#56]
Hey,  thanks for making the great prf-synthesize
I have a question that will the prf-synthesize simulate voxels with more than one receptive fields, as reported in "Carvalho, J., Invernizzi, A., Ahmadi, K., Hoffmann, M. B., Renken, R. J., & Cornelissen, F. W. (2020). Micro-probing enables fine-grained mapping of neuronal populations using fMRI. Neuroimage, 209, 116423. https://doi.org/10.1016/j.neuroimage.2019.116423"
If it can, then how could I make it
Thanks~

**Comment by garikoitz** [comment]
Hi,
if I understand correctly, it cannot be done with the code as it is, it
would require development.

Write me to garikoitz@gmail.com if you want to discuss it a little bit
more,
thanks!
Gari

**Comment by ustc-bmec** [comment]
Thanks for your response😊
